export const CATEGORIES = [
"Painting",
"Flooring",
"Tiles",
"Masonry",
"Cement",
"Sand",
"Concrete",
"Plaster",
"Steel",
"Plumbing",
"Electrical",
"False Ceiling",
"Kitchen",
"Furniture",
"Doors & Windows",
"Hardware",
"Other",
];

export const FORMULA_TYPES = [
{
value: "PAINT",
label: "Paint",
description:
"Net wall area × coats ÷ coverage per litre",
unit: "litre",
},
{
value: "WALL_PUTTY",
label: "Wall Putty",
description:
"Net wall area × coats × consumption",
unit: "kg",
},
{
value: "PRIMER",
label: "Primer",
description:
"Net wall area × coats ÷ coverage",
unit: "litre",
},
{
value: "FLOOR_TILE",
label: "Floor Tile",
description:
"Floor area ÷ tile area + wastage",
unit: "piece",
},
{
value: "WALL_TILE",
label: "Wall Tile",
description:
"Wall area ÷ tile area + wastage",
unit: "piece",
},
{
value: "TILE_ADHESIVE",
label: "Tile Adhesive",
description:
"Tile area × adhesive consumption",
unit: "kg",
},
{
value: "GROUT",
label: "Tile Grout",
description:
"Tile area × grout consumption",
unit: "kg",
},
{
value: "BRICKS",
label: "Bricks",
description:
"Wall volume ÷ brick volume with mortar/wastage adjustment",
unit: "piece",
},
{
value: "CEMENT_MORTAR",
label: "Cement for Mortar",
description:
"Masonry volume × mortar ratio × cement fraction",
unit: "bag",
},
{
value: "SAND_MORTAR",
label: "Sand for Mortar",
description:
"Masonry volume × mortar ratio × sand fraction",
unit: "cu ft",
},
{
value: "PLASTER_CEMENT",
label: "Plaster Cement",
description:
"Plaster area × thickness × mix ratio",
unit: "bag",
},
{
value: "PLASTER_SAND",
label: "Plaster Sand",
description:
"Plaster area × thickness × mix ratio",
unit: "cu ft",
},
{
value: "CONCRETE",
label: "Concrete",
description:
"Length × width × depth",
unit: "cu ft",
},
{
value: "STEEL",
label: "Steel",
description:
"Concrete volume × steel consumption",
unit: "kg",
},
{
value: "PIPE",
label: "Pipe",
description:
"Required running length + wastage",
unit: "ft",
},
{
value: "ELECTRICAL_POINT",
label: "Electrical Point",
description:
"Number of electrical points",
unit: "point",
},
{
value: "ELECTRICAL_WIRE",
label: "Electrical Wire",
description:
"Number of points × average wire length",
unit: "ft",
},
{
value: "CONDUIT",
label: "Electrical Conduit",
description:
"Number of points × average conduit length",
unit: "ft",
},
{
value: "FALSE_CEILING",
label: "False Ceiling",
description:
"Ceiling area + wastage",
unit: "sq ft",
},
{
value: "COUNTERTOP",
label: "Countertop",
description:
"Length × depth",
unit: "sq ft",
},
{
value: "BACKSPLASH",
label: "Backsplash",
description:
"Length × height",
unit: "sq ft",
},
{
value: "DOOR",
label: "Door",
description:
"Number of doors",
unit: "piece",
},
{
value: "WINDOW",
label: "Window",
description:
"Number of windows",
unit: "piece",
},
{
value: "QUANTITY",
label: "Quantity",
description:
"Direct number of pieces/items",
unit: "piece",
},
{
value: "RUNNING_FEET",
label: "Running Feet",
description:
"Direct running length",
unit: "running ft",
},
];

export const DEFAULT_PRODUCTS = [
{
id: "paint-interior",
category: "Painting",
product: "Interior Emulsion Paint",
formulaType: "PAINT",
rate: 450,
wastage: 5,
quality: "Standard",
status: "Active",
coverage: 120,
coats: 2,
},
{
id: "wall-putty",
category: "Painting",
product: "Wall Putty",
formulaType: "WALL_PUTTY",
rate: 45,
wastage: 5,
quality: "Standard",
status: "Active",
consumption: 1.5,
coats: 2,
},
{
id: "wall-primer",
category: "Painting",
product: "Wall Primer",
formulaType: "PRIMER",
rate: 280,
wastage: 5,
quality: "Standard",
status: "Active",
coverage: 120,
coats: 1,
},
{
id: "floor-tile",
category: "Flooring",
product: "Vitrified Floor Tile 2x4 ft",
formulaType: "FLOOR_TILE",
rate: 850,
wastage: 8,
quality: "Standard",
status: "Active",
tileLength: 2,
tileWidth: 4,
},
{
id: "wall-tile",
category: "Tiles",
product: "Bathroom Wall Tile 1x2 ft",
formulaType: "WALL_TILE",
rate: 180,
wastage: 8,
quality: "Standard",
status: "Active",
tileLength: 1,
tileWidth: 2,
},
{
id: "tile-adhesive",
category: "Tiles",
product: "Tile Adhesive",
formulaType: "TILE_ADHESIVE",
rate: 35,
wastage: 5,
quality: "Standard",
status: "Active",
consumption: 4,
},
{
id: "tile-grout",
category: "Tiles",
product: "Tile Grout",
formulaType: "GROUT",
rate: 80,
wastage: 5,
quality: "Standard",
status: "Active",
consumption: 0.15,
},
{
id: "brick",
category: "Masonry",
product: "Red Clay Brick",
formulaType: "BRICKS",
rate: 10,
wastage: 5,
quality: "Standard",
status: "Active",
brickLength: 0.75,
brickWidth: 0.375,
brickHeight: 0.25,
mortarAdjustment: 1.25,
},
{
id: "cement-mortar",
category: "Cement",
product: "Cement for Brick Masonry",
formulaType: "CEMENT_MORTAR",
rate: 420,
wastage: 5,
quality: "Standard",
status: "Active",
mortarRatio: 0.25,
cementFraction: 1 / 5,
bagVolume: 1.25,
},
{
id: "sand-mortar",
category: "Sand",
product: "Sand for Brick Masonry",
formulaType: "SAND_MORTAR",
rate: 65,
wastage: 5,
quality: "Standard",
status: "Active",
mortarRatio: 0.25,
sandFraction: 4 / 5,
},
{
id: "plaster-cement",
category: "Cement",
product: "Cement for Plaster",
formulaType: "PLASTER_CEMENT",
rate: 420,
wastage: 5,
quality: "Standard",
status: "Active",
plasterThickness: 0.5,
cementFraction: 1 / 5,
bagVolume: 1.25,
},
{
id: "plaster-sand",
category: "Sand",
product: "Sand for Plaster",
formulaType: "PLASTER_SAND",
rate: 65,
wastage: 5,
quality: "Standard",
status: "Active",
plasterThickness: 0.5,
sandFraction: 4 / 5,
},
{
id: "electrical-wire",
category: "Electrical",
product: "Copper Electrical Wire",
formulaType: "ELECTRICAL_WIRE",
rate: 12,
wastage: 5,
quality: "Standard",
status: "Active",
averageWirePerPoint: 20,
},
{
id: "conduit",
category: "Electrical",
product: "PVC Electrical Conduit",
formulaType: "CONDUIT",
rate: 18,
wastage: 5,
quality: "Standard",
status: "Active",
averageConduitPerPoint: 8,
},
{
id: "electrical-point",
category: "Electrical",
product: "Electrical Point",
formulaType: "ELECTRICAL_POINT",
rate: 250,
wastage: 0,
quality: "Standard",
status: "Active",
},
{
id: "plumbing-pipe",
category: "Plumbing",
product: "CPVC Plumbing Pipe",
formulaType: "PIPE",
rate: 90,
wastage: 5,
quality: "Standard",
status: "Active",
},
{
id: "false-ceiling",
category: "False Ceiling",
product: "Gypsum False Ceiling",
formulaType: "FALSE_CEILING",
rate: 120,
wastage: 5,
quality: "Standard",
status: "Active",
},
{
id: "countertop",
category: "Kitchen",
product: "Kitchen Countertop",
formulaType: "COUNTERTOP",
rate: 1800,
wastage: 5,
quality: "Premium",
status: "Active",
},
{
id: "backsplash",
category: "Kitchen",
product: "Kitchen Backsplash",
formulaType: "BACKSPLASH",
rate: 250,
wastage: 8,
quality: "Standard",
status: "Active",
},
{
id: "door",
category: "Doors & Windows",
product: "Interior Door",
formulaType: "DOOR",
rate: 8500,
wastage: 0,
quality: "Standard",
status: "Active",
},
{
id: "window",
category: "Doors & Windows",
product: "Aluminium Window",
formulaType: "WINDOW",
rate: 6500,
wastage: 0,
quality: "Standard",
status: "Active",
},
];
